### ISSUE TITLE
GR models in a semi-distributed way

### ISSUE THREAD

**Issue by odelaigue** [hllauca/GR2MSemiDistr#1]
All monthly, daily and hourly GR models can now run in semi-distibuted way using the official airGR R-package.

EGU-2121. [New airGR developments: semi-distribution and data assimilation](https://doi.org/10.5194/egusphere-egu21-1371)

An example on the [airGR website](https://hydrogr.github.io/airGR/page_5_sd_model.html)

**Comment by hllauca** [comment]
Thanks, thats good news. However, this package was develop a years ago, and provide a semi distributed approach of the GR2M model to be applied in large-sample studies such as https://doi.org/10.3390/w13081048
